from __future__ import annotations

# fund_settlement_batches.status
BATCH_STATUS_CREATED = "created"
BATCH_STATUS_PRICING_LOCKED = "pricing_locked"
BATCH_STATUS_PRICE_FIXED = "price_fixed"
BATCH_STATUS_GAS_CHECKING = "gas_checking"
BATCH_STATUS_GAS_READY = "gas_ready"
BATCH_STATUS_COLLECTING_BUY_USDT = "collecting_buy_usdt"
BATCH_STATUS_BUY_USDT_COLLECTED = "buy_usdt_collected"
BATCH_STATUS_AWAITING_POSITIVE_NET_EXECUTION = "awaiting_positive_net_execution"
BATCH_STATUS_AWAITING_NEGATIVE_NET_EXECUTION = "awaiting_negative_net_execution"
BATCH_STATUS_PENDING_CONFIRMATION = "pending_confirmation"
BATCH_STATUS_POSITIVE_NET_PROCESSING = "positive_net_processing"
BATCH_STATUS_POSITIVE_NET_ACCOUNTING_FINALIZED = "positive_net_accounting_finalized"
BATCH_STATUS_POSITIVE_CASH_SETTLEMENT_COMPLETED = "positive_cash_settlement_completed"
BATCH_STATUS_FAILED_REQUIRES_REVIEW = "failed_requires_review"
BATCH_STATUS_PAUSED_OPERATOR_ACTION_REQUIRED = "paused_operator_action_required"

# stage 23: negative-net settlement statuses
BATCH_STATUS_NEGATIVE_NET_TARGETS_CALCULATED = "negative_net_targets_calculated"
BATCH_STATUS_NEGATIVE_NET_SALE_PLANNED = "negative_net_sale_planned"
BATCH_STATUS_NEGATIVE_NET_SALE_PROCESSING = "negative_net_sale_processing"
BATCH_STATUS_NEGATIVE_NET_SALE_EXECUTED = "negative_net_sale_executed"
BATCH_STATUS_NEGATIVE_NET_MASTER_FLOW_PROCESSING = "negative_net_master_flow_processing"
BATCH_STATUS_NEGATIVE_NET_WITHDRAWAL_PENDING = "negative_net_withdrawal_pending"
BATCH_STATUS_NEGATIVE_NET_WITHDRAWAL_RECONCILING = "negative_net_withdrawal_reconciling"
BATCH_STATUS_NEGATIVE_NET_CASH_READY_FOR_PAYOUT = "negative_net_cash_ready_for_payout"
BATCH_STATUS_NEGATIVE_NET_PAYOUT_PROCESSING = "negative_net_payout_processing"
BATCH_STATUS_NEGATIVE_NET_PAYOUTS_CONFIRMED = "negative_net_payouts_confirmed"
BATCH_STATUS_AWAITING_BYBIT_WITHDRAWAL = "awaiting_bybit_withdrawal"
BATCH_STATUS_BYBIT_WITHDRAWAL_CONFIRMED = "bybit_withdrawal_confirmed"
BATCH_STATUS_SELLER_PAYOUT_PROCESSING = "seller_payout_processing"
BATCH_STATUS_NEGATIVE_NET_ACCOUNTING_FINALIZED = "negative_net_accounting_finalized"
BATCH_STATUS_NEGATIVE_CASH_SETTLEMENT_COMPLETED = "negative_cash_settlement_completed"


# fund_negative_bybit_flows.status
BYBIT_FLOW_STATUS_CREATED = "created"
BYBIT_FLOW_STATUS_PREFLIGHT_PASSED = "preflight_passed"
BYBIT_FLOW_STATUS_PREFLIGHT_FAILED_REQUIRES_REVIEW = "preflight_failed_requires_review"
BYBIT_FLOW_STATUS_UNIVERSAL_TRANSFER_MOCKED = "universal_transfer_mocked"
BYBIT_FLOW_STATUS_UNIVERSAL_TRANSFER_RECONCILED = "universal_transfer_reconciled"
BYBIT_FLOW_STATUS_WITHDRAWAL_MOCKED = "withdrawal_mocked"
BYBIT_FLOW_STATUS_WITHDRAWAL_RECONCILED = "withdrawal_reconciled"
BYBIT_FLOW_STATUS_SETTLEMENT_WALLET_RECEIPT_CONFIRMED = "settlement_wallet_receipt_confirmed"
BYBIT_FLOW_STATUS_COMPLETED = "completed"
BYBIT_FLOW_STATUS_FAILED_REQUIRES_REVIEW = "failed_requires_review"

# fund_negative_payout_batches.status
PAYOUT_BATCH_STATUS_CREATED = "created"
PAYOUT_BATCH_STATUS_GAS_CHECK_PASSED = "gas_check_passed"
PAYOUT_BATCH_STATUS_GAS_TOPUP_MOCKED = "gas_topup_mocked"
PAYOUT_BATCH_STATUS_GAS_READY = "gas_ready"
PAYOUT_BATCH_STATUS_PAUSED_OPERATOR_ACTION_REQUIRED = "paused_operator_action_required"
PAYOUT_BATCH_STATUS_PAYOUTS_PLANNED = "payouts_planned"
PAYOUT_BATCH_STATUS_PAYOUTS_MOCKED = "payouts_mocked"
PAYOUT_BATCH_STATUS_PAYOUTS_CONFIRMED = "payouts_confirmed"
PAYOUT_BATCH_STATUS_BALANCE_REFRESH_MOCKED = "balance_refresh_mocked"
PAYOUT_BATCH_STATUS_COMPLETED = "completed"
PAYOUT_BATCH_STATUS_FAILED_REQUIRES_REVIEW = "failed_requires_review"

# fund_negative_payout_legs.status
PAYOUT_LEG_STATUS_PLANNED = "planned"
PAYOUT_LEG_STATUS_PAYOUT_MOCKED = "payout_mocked"
PAYOUT_LEG_STATUS_PAYOUT_CONFIRMED = "payout_confirmed"
PAYOUT_LEG_STATUS_BALANCE_REFRESHED = "balance_refreshed"
PAYOUT_LEG_STATUS_SKIPPED_ZERO_AMOUNT = "skipped_zero_amount"
PAYOUT_LEG_STATUS_FAILED_REQUIRES_REVIEW = "failed_requires_review"

# fund_negative_payout_batches.gas_status
PAYOUT_GAS_STATUS_NOT_CHECKED = "not_checked"
PAYOUT_GAS_STATUS_SUFFICIENT = "sufficient"
PAYOUT_GAS_STATUS_TOPUP_REQUIRED = "topup_required"
PAYOUT_GAS_STATUS_TOPUP_MOCKED = "topup_mocked"
PAYOUT_GAS_STATUS_READY = "ready"
PAYOUT_GAS_STATUS_INSUFFICIENT_OK_GAS = "insufficient_ok_gas"
PAYOUT_GAS_STATUS_FAILED_REQUIRES_REVIEW = "failed_requires_review"

# fund_negative_payout_batches.balance_refresh_status
PAYOUT_BALANCE_REFRESH_STATUS_NOT_STARTED = "not_started"
PAYOUT_BALANCE_REFRESH_STATUS_MOCKED = "mocked"
PAYOUT_BALANCE_REFRESH_STATUS_CONFIRMED = "confirmed"
PAYOUT_BALANCE_REFRESH_STATUS_FAILED_REQUIRES_REVIEW = "failed_requires_review"

# fund_negative_finalization_batches.status
FINALIZATION_BATCH_STATUS_CREATED = "created"
FINALIZATION_BATCH_STATUS_VALIDATING = "validating"
FINALIZATION_BATCH_STATUS_ACCOUNTING_PROCESSING = "accounting_processing"
FINALIZATION_BATCH_STATUS_ACCOUNTING_FINALIZED = "accounting_finalized"
FINALIZATION_BATCH_STATUS_PRICING_UNLOCKED = "pricing_unlocked"
FINALIZATION_BATCH_STATUS_COMPLETED = "completed"
FINALIZATION_BATCH_STATUS_FAILED_REQUIRES_REVIEW = "failed_requires_review"

# fund_negative_sale_batches.status
SALE_BATCH_STATUS_SNAPSHOT_CREATED = "snapshot_created"
SALE_BATCH_STATUS_SALE_PLAN_CREATED = "sale_plan_created"
SALE_BATCH_STATUS_SALE_PLAN_FAILED_REQUIRES_REVIEW = "sale_plan_failed_requires_review"
SALE_BATCH_STATUS_SALE_EXECUTION_PROCESSING = "sale_execution_processing"
SALE_BATCH_STATUS_SALE_EXECUTION_COMPLETED = "sale_execution_completed"
SALE_BATCH_STATUS_SALE_EXECUTION_COMPLETED_WITH_EXTRA_SALE = "sale_execution_completed_with_extra_sale"
SALE_BATCH_STATUS_SALE_EXECUTION_FAILED_REQUIRES_REVIEW = "sale_execution_failed_requires_review"

# fund_negative_sale_legs.status
SALE_LEG_STATUS_PLANNED = "planned"
SALE_LEG_STATUS_SKIPPED_ZERO_VALUE = "skipped_zero_value"
SALE_LEG_STATUS_SKIPPED_NOT_ELIGIBLE = "skipped_not_eligible"
SALE_LEG_STATUS_SKIPPED_MIN_ORDER = "skipped_min_order"
SALE_LEG_STATUS_SKIPPED_SYMBOL_NOT_TRADING = "skipped_symbol_not_trading"
SALE_LEG_STATUS_SKIPPED_LIQUIDITY_GUARD = "skipped_liquidity_guard"
SALE_LEG_STATUS_SKIPPED_MARGIN_GUARD = "skipped_margin_guard"
SALE_LEG_STATUS_CASH_AVAILABLE = "cash_available"
SALE_LEG_STATUS_BUFFER_AVAILABLE = "buffer_available"
SALE_LEG_STATUS_FAILED_REQUIRES_REVIEW = "failed_requires_review"
SALE_LEG_STATUS_MARKET_ORDER_MOCKED = "market_order_mocked"
SALE_LEG_STATUS_NATIVE_ICEBERG_MOCKED = "native_iceberg_mocked"
SALE_LEG_STATUS_SLICED_IOC_MOCKED = "sliced_ioc_mocked"
SALE_LEG_STATUS_FILLED = "filled"
SALE_LEG_STATUS_PARTIAL_FILLED_ACCEPTED = "partial_filled_accepted"
SALE_LEG_STATUS_PARTIAL_FILLED_BELOW_THRESHOLD = "partial_filled_below_threshold"
SALE_LEG_STATUS_RESIDUALIZED = "residualized"
SALE_LEG_STATUS_USDT_EARN_REDEEMED = "usdt_earn_redeemed"
SALE_LEG_STATUS_USDT_EARN_REDEEM_MOCKED = "usdt_earn_redeem_mocked"
SALE_LEG_STATUS_EXTRA_SALE_PLANNED = "extra_sale_planned"
SALE_LEG_STATUS_EXTRA_SALE_MOCKED = "extra_sale_mocked"
SALE_LEG_STATUS_PENDING_CONFIRMATION = "pending_confirmation"

BATCH_STATUS_NO_ORDERS = "no_orders"
BATCH_STATUS_FAILED = "failed"

BATCH_TERMINAL_STATUSES = {
    BATCH_STATUS_AWAITING_POSITIVE_NET_EXECUTION,
    BATCH_STATUS_AWAITING_NEGATIVE_NET_EXECUTION,
    BATCH_STATUS_POSITIVE_NET_ACCOUNTING_FINALIZED,
    BATCH_STATUS_POSITIVE_CASH_SETTLEMENT_COMPLETED,
    BATCH_STATUS_NO_ORDERS,
    BATCH_STATUS_FAILED,
    BATCH_STATUS_FAILED_REQUIRES_REVIEW,
}

# fund_orders.status
ORDER_STATUS_PENDING = "pending"
ORDER_STATUS_SETTLING = "settling"
ORDER_STATUS_BUY_COLLECTING = "buy_collecting"
ORDER_STATUS_BUY_COLLECTED = "buy_collected"
ORDER_STATUS_AWAITING_POSITIVE_NET_EXECUTION = "awaiting_positive_net_execution"
ORDER_STATUS_AWAITING_NEGATIVE_NET_EXECUTION = "awaiting_negative_net_execution"
ORDER_STATUS_PROCESSING = "processing"
ORDER_STATUS_SUCCESS = "success"
ORDER_STATUS_FAILED = "failed"
ORDER_STATUS_FAILED_REQUIRES_REVIEW = "failed_requires_review"
ORDER_STATUS_CANCELLED = "cancelled"

# fund_orders.side
ORDER_SIDE_BUY = "buy"
ORDER_SIDE_REDEEM = "redeem"

# fund_settlement_transfers.transfer_type
TRANSFER_TYPE_SETTLEMENT_WALLET_GAS_TOPUP = "settlement_wallet_gas_topup"
TRANSFER_TYPE_USER_WALLET_GAS_TOPUP = "user_wallet_gas_topup"
TRANSFER_TYPE_USER_BUY_USDT_TO_SETTLEMENT = "user_buy_usdt_to_settlement"
TRANSFER_TYPE_REDEEM_PAYOUT_SETTLEMENT_TO_USER_WALLET = "redeem_payout_settlement_to_user_wallet"
TRANSFER_TYPE_POSITIVE_NET_SETTLEMENT_TO_BYBIT_SUBACCOUNT = "positive_net_settlement_to_bybit_subaccount"
TRANSFER_TYPE_BYBIT_FUND_TO_UNIFIED_INTERNAL_TRANSFER = "bybit_fund_to_unified_internal_transfer"

# fund_settlement_transfers.status
TRANSFER_STATUS_PENDING = "pending"
TRANSFER_STATUS_PREPARED = "prepared"
TRANSFER_STATUS_PROCESSING = "processing"
TRANSFER_STATUS_WAITING_FOR_GAS = "waiting_for_gas"
TRANSFER_STATUS_SENT = "sent"
TRANSFER_STATUS_CONFIRMED = "confirmed"
TRANSFER_STATUS_FAILED = "failed"
TRANSFER_STATUS_SKIPPED = "skipped"
TRANSFER_STATUS_PENDING_CONFIRMATION = "pending_confirmation"
TRANSFER_STATUS_FAILED_REQUIRES_REVIEW = "failed_requires_review"

WALLET_TRANSFER_STATUS_PENDING = "pending"
WALLET_TRANSFER_STATUS_PROCESSING = "processing"
WALLET_TRANSFER_STATUS_WAITING_FOR_GAS = "waiting_for_gas"
WALLET_TRANSFER_STATUS_SUCCESS = "success"
WALLET_TRANSFER_STATUS_FAILED = "failed"

FEE_WALLET_SWAP_STATUS_PENDING = "pending"
FEE_WALLET_SWAP_STATUS_SUCCESS = "success"
FEE_WALLET_SWAP_STATUS_FAILED = "failed"
FEE_WALLET_SWAP_STATUS_SKIPPED = "skipped"
FEE_WALLET_SWAP_STATUS_WAITING_FOR_GAS = "waiting_for_gas"

PLATFORM_EMERGENCY_LOCK_STATUS_ACTIVE = "active"
PLATFORM_EMERGENCY_LOCK_STATUS_RESOLVED = "resolved"

BYBIT_WITHDRAWAL_WATCHDOG_DECISION_ALLOWED = "allowed"
BYBIT_WITHDRAWAL_WATCHDOG_DECISION_UNEXPECTED = "unexpected"
BYBIT_WITHDRAWAL_WATCHDOG_DECISION_CANCEL_ATTEMPTED = "cancel_attempted"
BYBIT_WITHDRAWAL_WATCHDOG_DECISION_CANCEL_SUCCESS = "cancel_success"
BYBIT_WITHDRAWAL_WATCHDOG_DECISION_CANCEL_FAILED = "cancel_failed"
BYBIT_WITHDRAWAL_WATCHDOG_DECISION_API_UNAVAILABLE_FAIL_CLOSED = "api_unavailable_fail_closed"

# fund_runtime_state
PRICING_LOCK_REASON_SETTLEMENT = "settlement"