from __future__ import annotations

# action_type
OP_GUARD_ACTION_BYBIT_UNIVERSAL_TRANSFER = "bybit_universal_transfer"
OP_GUARD_ACTION_BYBIT_MASTER_WITHDRAWAL = "bybit_master_withdrawal"
OP_GUARD_ACTION_BSC_REDEEM_PAYOUT = "bsc_redeem_payout"
OP_GUARD_ACTION_BSC_SETTLEMENT_GAS_TOPUP = "bsc_settlement_gas_topup"
OP_GUARD_ACTION_BSC_POSITIVE_NET_TO_BYBIT = "bsc_positive_net_to_bybit"

OP_GUARD_ACTION_TYPES = {
    OP_GUARD_ACTION_BYBIT_UNIVERSAL_TRANSFER,
    OP_GUARD_ACTION_BYBIT_MASTER_WITHDRAWAL,
    OP_GUARD_ACTION_BSC_REDEEM_PAYOUT,
    OP_GUARD_ACTION_BSC_SETTLEMENT_GAS_TOPUP,
    OP_GUARD_ACTION_BSC_POSITIVE_NET_TO_BYBIT,
}

# scope_type
OP_GUARD_SCOPE_GLOBAL = "global"
OP_GUARD_SCOPE_FUND = "fund"

# mode
OP_GUARD_MODE_BLOCKED = "blocked"
OP_GUARD_MODE_LIVE_ALLOWED = "live_allowed"

# override status
OP_GUARD_OVERRIDE_STATUS_ACTIVE = "active"
OP_GUARD_OVERRIDE_STATUS_USED = "used"
OP_GUARD_OVERRIDE_STATUS_EXPIRED = "expired"
OP_GUARD_OVERRIDE_STATUS_REVOKED = "revoked"

# event decision
OP_GUARD_DECISION_ALLOWED = "allowed"
OP_GUARD_DECISION_BLOCKED = "blocked"
OP_GUARD_DECISION_ERROR = "error"