from __future__ import annotations

# action_type
OP_GUARD_ACTION_BYBIT_UNIVERSAL_TRANSFER = "bybit_universal_transfer"
OP_GUARD_ACTION_BYBIT_MASTER_WITHDRAWAL = "bybit_master_withdrawal"
OP_GUARD_ACTION_BSC_REDEEM_PAYOUT = "bsc_redeem_payout"
OP_GUARD_ACTION_BSC_SETTLEMENT_GAS_TOPUP = "bsc_settlement_gas_topup"
OP_GUARD_ACTION_BSC_POSITIVE_NET_TO_BYBIT = "bsc_positive_net_to_bybit"
OP_GUARD_ACTION_BSC_BUY_COLLECTION_GAS_TOPUP = "bsc_buy_collection_gas_topup"
OP_GUARD_ACTION_BSC_BUY_COLLECTION_USDT_TO_SETTLEMENT = (
    "bsc_buy_collection_usdt_to_settlement"
)
OP_GUARD_ACTION_BYBIT_NEGATIVE_SALE_ORDER = "bybit_negative_sale_order"
OP_GUARD_ACTION_BYBIT_EARN_REDEEM = "bybit_earn_redeem"
OP_GUARD_ACTION_BYBIT_ALLOCATION_TRADE_ORDER = "bybit_allocation_trade_order"
OP_GUARD_ACTION_BYBIT_ALLOCATION_STRATEGY_ORDER = "bybit_allocation_strategy_order"
OP_GUARD_ACTION_BYBIT_ALLOCATION_EARN_ORDER = "bybit_allocation_earn_order"
OP_GUARD_ACTION_BYBIT_ALLOCATION_TRANSFER = "bybit_allocation_transfer"

OP_GUARD_ACTION_TYPES = {
    OP_GUARD_ACTION_BYBIT_UNIVERSAL_TRANSFER,
    OP_GUARD_ACTION_BYBIT_MASTER_WITHDRAWAL,
    OP_GUARD_ACTION_BSC_REDEEM_PAYOUT,
    OP_GUARD_ACTION_BSC_SETTLEMENT_GAS_TOPUP,
    OP_GUARD_ACTION_BSC_POSITIVE_NET_TO_BYBIT,
    OP_GUARD_ACTION_BSC_BUY_COLLECTION_GAS_TOPUP,
    OP_GUARD_ACTION_BSC_BUY_COLLECTION_USDT_TO_SETTLEMENT,
    OP_GUARD_ACTION_BYBIT_NEGATIVE_SALE_ORDER,
    OP_GUARD_ACTION_BYBIT_EARN_REDEEM,
    OP_GUARD_ACTION_BYBIT_ALLOCATION_TRADE_ORDER,
    OP_GUARD_ACTION_BYBIT_ALLOCATION_STRATEGY_ORDER,
    OP_GUARD_ACTION_BYBIT_ALLOCATION_EARN_ORDER,
    OP_GUARD_ACTION_BYBIT_ALLOCATION_TRANSFER,
}

# scope_type
OP_GUARD_SCOPE_GLOBAL = "global"
OP_GUARD_SCOPE_FUND = "fund"

# mode
OP_GUARD_MODE_BLOCKED = "blocked"
OP_GUARD_MODE_LIVE_ALLOWED = "live_allowed"

# override status
OP_GUARD_OVERRIDE_STATUS_ACTIVE = "active"
OP_GUARD_OVERRIDE_STATUS_USED = "used"
OP_GUARD_OVERRIDE_STATUS_EXPIRED = "expired"
OP_GUARD_OVERRIDE_STATUS_REVOKED = "revoked"

# event decision
OP_GUARD_DECISION_ALLOWED = "allowed"
OP_GUARD_DECISION_BLOCKED = "blocked"
OP_GUARD_DECISION_ERROR = "error"